backend:
  name: git-gateway
  branch: master

media_folder: "static/images/softwares" 
public_folder: "/images/softwares"

collections:
  - label: "Softwares"
    name: "softwares"
    extension: "json"
    files:
      - label: "Softwares"
        name: "softwares"
        file: "data/softwares.json"
        fields:
          - label: "Softwares List"
            name: "softwares"
            widget: "list"
            fields:
            - {label: Id, name: id, widget: string}
            - {label: Name, name: name, widget: string}
            - {label: Description, name: description, widget: text}
            - {label: Eligibility, name: eligibility, widget: text}
            - {label: Url, name: url, widget: string}
            - {label: Image, name: image, widget: image}