backend:
  name: git-gateway
  branch: dev
  squash_merges: true

media_folder: "static/images/softwares" 
public_folder: "/images/softwares"
site_url: https://softwaredonation.org/

collections:
  - label: "Softwares"
    name: "softwares"
    extension: "json"
    files:
      - label: "Softwares"
        name: "softwares"
        file: "data/softwares.json"
        fields:
          - label: "Softwares List"
            name: "softwares"
            widget: "list"
            fields:
            - {label: Id, name: id, widget: string}
            - {label: Name, name: name, widget: string}
            - {label: Description, name: description, widget: text}
            - {label: Eligibility, name: eligibility, widget: text}
            - {label: Url, name: url, widget: string}
            - {label: Image, name: image, widget: image}
  - label: "Causes"
    name: "causes"
    extension: "json"
    files:
      - label: "Causes"
        name: "causes"
        file: "data/causes.json"
        fields:
          - label: "Causes List"
            name: "causes"
            widget: "list"
            fields:
            - {label: Id, name: id, widget: string}
            - {label: Name, name: name, widget: string}
  - label: "Softwares per cause"
    name: "softwares-cause"
    folder: "data/causes"
    create: true
    extension: "json"
    identifier_field: title
    fields:
      - {label: Cause Id, name: title, widget: string}
      - label: "Category list"
        name: "categories"
        widget: "list"
        fields:
          - {label: Category name, name: name, widget: string}
          - label: "Sofwares"
            name: "softwares"
            widget: "list"
            fields:
              - {label: Software Id, name: id, widget: string}